#!/usr/bin/env python3
import os
import subprocess
from pyfiglet import figlet_format 
import importlib
import sys
import cmd
command=[]
class CmdParse(cmd.Cmd):
    prompt="\033[1;31m[s3v3n_k17 ;)]~# \033[1;00m"
    def do_listall(seld,line):
        print(command)
    def help_me(self):
        print("\n"+" "*15 + "[HELP]")
        print(" "+"="*36+"\n")
        print(" [1]\033[94m[discover]\033[00m \n [?] Discover Devices On your network \n "+"-"*35)
        print(" [2]\033[94m[portscan]\033[00m \n [?] Run a Port Scan On Specific Target \n "+"-"*35)
        print(" [3]\033[94m[ncconnect]\033[00m \n [?] Establishes a netcat connection \n "+"-"*35)
        print(" [4]\033[94m[nclisten]\033[00m \n [?] Starts a netcat listener \n "+"-"*35)
        print(" [5]\033[94m[exit]\033[00m \n [?] Exit out of program \n "+"-"*35)

    def default(self, line):
        commandline(line)
        command.append(line)
def networkscanner():
    #subprocess.call("python3 ./tool/pingsweeper.py")
    sys.path.insert(1, 'tool/')
    import discover
    discover.run()
def portscanner():
    sys.path.insert(1,'tool/')
    import scanner
    scanner.run()
def nclisten():
    sys.path.insert(1,'tool/')
    import netcat
    netcat.listener()
def ncconnect():
    sys.path.insert(1,'tool/')
    import netcat
    netcat.connect()
def commandline(opt):
    #opt = (input("\033[1;31m[s3v3n_k17 ;)]~# \033[1;00m"))
    if (opt == "discover"):
        networkscanner()
    elif (opt == "portscan"):
        portscanner()
    elif (opt == "exit" or opt == "Exit" or opt == "quit"):
        print("[;)]Exiting Now.....")
        exit()
    elif(opt ==  "clear"):
        subprocess.call('clear')
        banner()
    elif(opt ==  "ls"):
        subprocess.call("ls")
    elif(opt=="help"):
        banner()
    elif(opt == "ncconnect"):
        ncconnect()
    elif(opt == "nclisten"):
        nclisten()
    else:
        try:
            subprocess.call(opt)
        except:
            print ("Incorrect Command")
    #else:
    #    print("Invalid Input")
    opt=" "
def banner():
    t2 = "  =================================================================== "
    b2 = " "*28 + "S3V3N_K17" 
    cust_fig = figlet_format(b2,font='digital' )
    print("\033[92m"+cust_fig+"\033[00m")
    #print(t2)
def nmapscanner():
    subprocess.call('python3 nmapscanner.py')
if __name__ == "__main__":
    rows, columns = os.popen('stty size', 'r').read().split()
    rows = int(rows)
    subprocess.call('clear')
    banner()
    CmdParse().cmdloop()
    #commandline()
